# Generated by Django 5.0.6 on 2024-06-18 06:11

import home.model_field_validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.PositiveIntegerField(validators=[home.model_field_validations.unit_price_validation]),
        ),
    ]
