# Generated by Django 5.0.7 on 2024-07-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_comment_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='total_com_disliked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='total_com_liked',
            field=models.IntegerField(default=0),
        ),
    ]
