# Generated by Django 5.0.7 on 2024-07-24 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_comment_total_com_disliked_comment_total_com_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='total_com_disliked',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='total_com_liked',
        ),
        migrations.RemoveField(
            model_name='product',
            name='like_product',
        ),
    ]
