# Generated by Django 5.0.7 on 2024-07-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_comment_total_com_disliked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenu',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True),
        ),
    ]
