# Generated by Django 5.0.7 on 2024-08-13 09:30

import home.model_field_validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricechange',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[home.model_field_validations.unit_price_validation]),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[home.model_field_validations.unit_price_validation]),
        ),
        migrations.AlterField(
            model_name='variant',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[home.model_field_validations.unit_price_validation]),
        ),
    ]
