# Generated by Django 5.0.7 on 2024-08-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order_address_order_first_name_order_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('discount', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
