# Generated by Django 5.0.7 on 2024-08-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_remove_order_cart_number_order_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='error',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
